# Generated by Django 5.1.3 on 2024-11-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamsafarem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companion',
            name='date',
        ),
        migrations.RemoveField(
            model_name='companion',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='companion',
            name='start_location',
        ),
    ]
